# Generated by Django 5.2.6 on 2025-09-18 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chercheur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/photoTeam/'),
        ),
        migrations.CreateModel(
            name='CandidatureParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_candidat', models.CharField(max_length=255, verbose_name='Nom de famille')),
                ('prenom_candidat', models.CharField(max_length=255, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('telephone_candidat', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email_candidat', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('adresse_complete', models.TextField(verbose_name='Adresse complète')),
                ('ville_residence', models.CharField(max_length=255, verbose_name='Ville de résidence')),
                ('pays_residence', models.CharField(max_length=100, verbose_name='Pays de résidence')),
                ('niveau_etude_actuel', models.CharField(choices=[('Licence', 'Licence (Bac+3)'), ('Master 1', 'Master 1 (Bac+4)'), ('Master 2', 'Master 2 (Bac+5)'), ('Doctorat', 'Doctorat (Bac+8)'), ('Autre', 'Autre niveau')], max_length=50, verbose_name="Niveau d'étude actuel")),
                ('etablissement_origine', models.CharField(max_length=255, verbose_name="Établissement d'origine")),
                ('filiere_etude', models.CharField(max_length=255, verbose_name="Filière d'étude")),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne générale (/20)')),
                ('annee_obtention_diplome', models.PositiveIntegerField(verbose_name="Année d'obtention du diplôme")),
                ('cv_candidat', models.FileField(upload_to='static/candidatures/cv/', verbose_name='Curriculum Vitae (PDF)')),
                ('lettre_motivation', models.FileField(upload_to='static/candidatures/lettres/', verbose_name='Lettre de motivation (PDF)')),
                ('releves_notes', models.FileField(upload_to='static/candidatures/notes/', verbose_name='Relevés de notes (PDF)')),
                ('diplome_obtenu', models.FileField(blank=True, null=True, upload_to='static/candidatures/diplomes/', verbose_name='Copie du diplôme (PDF)')),
                ('motivation_principale', models.CharField(choices=[('Recherche académique', 'Intérêt pour la recherche académique'), ('Application industrielle', "Application dans l'industrie"), ('Développement personnel', 'Développement des compétences personnelles'), ('Innovation technologique', "Contribution à l'innovation technologique"), ('Impact social', 'Créer un impact social positif')], max_length=100, verbose_name='Motivation principale')),
                ('projet_professionnel', models.TextField(help_text="Décrivez votre projet professionnel et comment ce parcours s'y intègre", verbose_name='Projet professionnel (500 mots max)')),
                ('experience_recherche', models.TextField(blank=True, help_text='Décrivez vos expériences précédentes en recherche (stages, projets, publications)', null=True, verbose_name='Expérience en recherche')),
                ('competences_techniques', models.TextField(blank=True, help_text='Listez vos compétences techniques pertinentes pour ce parcours', null=True, verbose_name='Compétences techniques')),
                ('statut_candidature', models.CharField(choices=[('En attente', 'En attente de traitement'), ("En cours d'examen", "En cours d'examen"), ('Acceptée', 'Candidature acceptée'), ('Refusée', 'Candidature refusée'), ("Liste d'attente", "En liste d'attente")], default='En attente', max_length=50, verbose_name='Statut de la candidature')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_derniere_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('commentaires_admin', models.TextField(blank=True, help_text='Commentaires internes pour le suivi de la candidature', null=True, verbose_name='Commentaires administratifs')),
                ('note_evaluation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name="Note d'évaluation (/20)")),
                ('id_parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoireparcour', verbose_name='Parcours demandé')),
            ],
            options={
                'verbose_name': 'Candidature au parcours',
                'verbose_name_plural': 'Candidatures aux parcours',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
