# Generated by Django 5.2.6 on 2025-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chercheur_photo_candidatureparcours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatureparcours',
            name='competences_techniques',
        ),
        migrations.RemoveField(
            model_name='candidatureparcours',
            name='experience_recherche',
        ),
        migrations.AddField(
            model_name='candidatureparcours',
            name='attentes_formation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatureparcours',
            name='motivation_principale',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatureparcours',
            name='projet_professionnel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
