# Generated by Django 5.2.6 on 2025-09-22 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_laboratoireparcour_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recherche',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Recherche', 'verbose_name_plural': 'Recherches'},
        ),
        migrations.AddField(
            model_name='recherche',
            name='domaine_recherche',
            field=models.ForeignKey(blank=True, help_text='Domaine principal de cette recherche', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.domaine', verbose_name='Domaine de recherche'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='mots_cles',
            field=models.TextField(blank=True, help_text='Mots-clés séparés par des virgules', null=True, verbose_name='Mots-clés'),
        ),
        migrations.AddField(
            model_name='recherche',
            name='source_financement',
            field=models.CharField(blank=True, choices=[('Public', 'Financement public'), ('Privé', 'Financement privé'), ('Mixte', 'Financement mixte'), ('International', 'Financement international'), ('Auto-financé', 'Auto-financé')], max_length=50, null=True, verbose_name='Source de financement'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Budget total'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='creer_le',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_debut',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin prévue'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin réelle'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='mise_a_jour_le',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='statu',
            field=models.CharField(choices=[('Planifier', 'Planifiér'), ('En cours', 'En cours'), ('Terminer', 'Terminer'), ('Suspendu', 'Suspendu'), ('Annuler', 'Annuler')], default='Planifier', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre de la recherche'),
        ),
    ]
