# Generated by Django 5.2.6 on 2025-09-22 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recherche_options_recherche_domaine_recherche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact', models.CharField(choices=[('principal', 'Contact principal'), ('direction', 'Direction'), ('administration', 'Administration'), ('recherche', 'Service recherche'), ('partenariats', 'Partenariats'), ('communication', 'Communication')], default='principal', max_length=30)),
                ('adresse_complete', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.CharField(max_length=100)),
                ('telephone_principal', models.CharField(blank=True, max_length=30, null=True)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=30, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_secondaire', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nom_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('fonction_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='HoraireLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')])),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('est_ferme', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('creer_le', models.DateTimeField(auto_now_add=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('contact_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contactlaboratoire')),
            ],
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_expediteur', models.CharField(max_length=100)),
                ('nom_expediteur', models.CharField(max_length=100)),
                ('email_expediteur', models.EmailField(max_length=254)),
                ('organisation_expediteur', models.CharField(blank=True, max_length=255, null=True)),
                ('sujet_message', models.CharField(max_length=255)),
                ('contenu_message', models.TextField()),
                ('statut_message', models.CharField(choices=[('nouveau', 'Nouveau message'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20)),
                ('reponse_admin', models.TextField(blank=True, null=True)),
                ('responsable_reponse', models.CharField(blank=True, max_length=150, null=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('est_traite', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_modification', models.DateTimeField(auto_now=True)),
                ('id_laboratoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoire')),
            ],
        ),
    ]
