# Generated by Django 5.2.6 on 2025-09-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contactlaboratoire_horairelaboratoire_messagecontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='email_secondaire',
        ),
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='fonction_contact',
        ),
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='nom_contact',
        ),
        migrations.RemoveField(
            model_name='contactlaboratoire',
            name='telephone_secondaire',
        ),
    ]
