# Generated by Django 5.2.6 on 2025-09-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_contactlaboratoire_email_secondaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlaboratoire',
            options={'verbose_name': 'Contact laboratoire', 'verbose_name_plural': 'Contacts laboratoires'},
        ),
        migrations.AlterModelOptions(
            name='horairelaboratoire',
            options={'ordering': ['contact_laboratoire', 'jour_semaine'], 'verbose_name': 'Horaire laboratoire', 'verbose_name_plural': 'Horaires laboratoires'},
        ),
        migrations.AlterModelOptions(
            name='messagecontact',
            options={'ordering': ['-date_envoi'], 'verbose_name': 'Message de contact', 'verbose_name_plural': 'Messages de contact'},
        ),
        migrations.AlterModelOptions(
            name='recherche',
            options={},
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='adresse_complete',
            field=models.CharField(max_length=255, verbose_name='Adresse complète'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='code_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='email_principal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email principal'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Contact actif'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='id_laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoire', verbose_name='Laboratoire'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='pays',
            field=models.CharField(max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='site_web',
            field=models.URLField(blank=True, null=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='telephone_principal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone principal'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='type_contact',
            field=models.CharField(choices=[('principal', 'Contact principal'), ('direction', 'Direction'), ('administration', 'Administration'), ('recherche', 'Service recherche'), ('partenariats', 'Partenariats'), ('communication', 'Communication')], default='principal', max_length=30, verbose_name='Type de contact'),
        ),
        migrations.AlterField(
            model_name='contactlaboratoire',
            name='ville',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='contact_laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contactlaboratoire', verbose_name='Contact laboratoire'),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='est_ferme',
            field=models.BooleanField(default=False, verbose_name='Fermé ce jour'),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fermeture'),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True, verbose_name="Heure d'ouverture"),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='jour_semaine',
            field=models.IntegerField(choices=[(1, 'Lundi'), (2, 'Mardi'), (3, 'Mercredi'), (4, 'Jeudi'), (5, 'Vendredi'), (6, 'Samedi'), (7, 'Dimanche')], verbose_name='Jour de la semaine'),
        ),
        migrations.AlterField(
            model_name='horairelaboratoire',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='contenu_message',
            field=models.TextField(verbose_name='Contenu du message'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_derniere_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='date_reponse',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='email_expediteur',
            field=models.EmailField(max_length=254, verbose_name="Email de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='est_traite',
            field=models.BooleanField(default=False, verbose_name='Message traité'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='id_laboratoire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.laboratoire', verbose_name='Laboratoire destinataire'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='nom_expediteur',
            field=models.CharField(max_length=100, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='organisation_expediteur',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Organisation de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='prenom_expediteur',
            field=models.CharField(max_length=100, verbose_name="Prénom de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='priorite',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='reponse_admin',
            field=models.TextField(blank=True, null=True, verbose_name='Réponse administrative'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='responsable_reponse',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Responsable de la réponse'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='statut_message',
            field=models.CharField(choices=[('nouveau', 'Nouveau message'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=20, verbose_name='Statut du message'),
        ),
        migrations.AlterField(
            model_name='messagecontact',
            name='sujet_message',
            field=models.CharField(max_length=255, verbose_name='Sujet du message'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='budget_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='creer_le',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_fin_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='date_fin_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='domaine_recherche',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Domaine de recherche'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='mise_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='mots_cles',
            field=models.TextField(blank=True, help_text='Séparez les mots-clés par des virgules', null=True, verbose_name='Mots-clés'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='source_financement',
            field=models.CharField(blank=True, choices=[('Public', 'Financement public'), ('Privé', 'Financement privé'), ('Mixte', 'Financement mixte'), ('International', 'Financement international'), ('Autofinancement', 'Autofinancement')], max_length=50, null=True, verbose_name='Source de financement'),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='statu',
            field=models.CharField(choices=[('Planifier', 'Planifiér'), ('En cours', 'En cours'), ('Terminer', 'Terminer'), ('Suspendu', 'Suspendu'), ('Annuler', 'Annuler')], default='Planifier', max_length=20),
        ),
        migrations.AlterField(
            model_name='recherche',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
