# Generated by Django 5.2.6 on 2025-09-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_contactlaboratoire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlaboratoire',
            name='mot_de_passe_email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mot de passe email'),
        ),
    ]
